# Generated by Django 5.0.3 on 2024-03-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afatafront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociacaoParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('regiao_atuante', models.CharField(max_length=100)),
                ('informacoes_gerais', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
